# Generated by Django 4.2 on 2023-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_of_birth', models.DateField()),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
